baseURL = 'https://tuo-username.github.io/'
languageCode = 'it-it'
title = 'Leonardo Mannini'
theme = 'ananke'

[params]
  description = "Il sito personale di Leonardo Mannini"
  author = "Leonardo Mannini"